### ISSUE TITLE
Release with support for 4.11

### ISSUE THREAD

**Issue by mseri** [ocaml-ppx/ppx_deriving_yojson#123]
Given the efforts in #121 and #122, is there anything blocking a release of `ppx_deriving_yojson` with support for ocaml 4.11?

**Comment by kit-ty-kate** [comment]
cc @gasche could make a tag? I'll publish the release if you want.

**Comment by gasche** [comment]
I can do it today (but it has to be today because I will be in holidays tomorrow). Another way to go would be to give one of you (@mseri or @kit-ty-kate; or @thierry-martinez) enough privilege on the repository so that you can do it yourself, and possibly lend a hand in the future. Is this a responsibility that you would accept?

**Comment by kit-ty-kate** [comment]
sure, I wouldn't mind

**Comment by mseri** [comment]
Same for me

**Comment by gasche** [comment]
I gave rights to all three of view; thanks for being willing to help! I prefer to discuss big changes beforehand, but in this case tagging a release for the minimal-changes-for-4.11 is a no-brainer, so please feel free to go ahead and do it.

I detailed my own release workflow in https://github.com/ocaml-ppx/ppx_deriving/pull/226#issuecomment-633228817 ; maybe you will find it inspiring. I understand that in this case @kit-ty-kate has already done testing of revdeps, so maybe this level of care is not necessary (but then maybe there could be issues with non-4.11-related metadata issues to fix?)

**Comment by kit-ty-kate** [comment]
Release done here and now merged: https://github.com/ocaml/opam-repository/pull/16917. Thanks everyone!
